name: push
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    env:
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSE_PROJECT_NAME: govcms8
      DEPLOY_BRANCH: 1.x

    steps:

      - uses: actions/checkout@v2

      - name: Docker-compose validate
        run: docker-compose config -q

      - name: Update codebase to follow CI configuration
        run: |
              sed -i -e "/###/d" docker-compose.yml
              cp .env.default .env
      
      - name: Start amazeeio-network
        run: docker network prune -f && docker network inspect amazeeio-network >/dev/null || docker network create amazeeio-network

      - name: Start GovCMS
        run: docker-compose up -d

      - name: Wait for MariaDb to be ready
        run: docker-compose exec -T cli dockerize -wait tcp://mariadb:3306 -timeout 1m || sleep 10

      - name: Install site
        run: docker-compose exec -T cli drush si -y govcms --site-name='Welcome to GovCMS' install_configure_form.enable_update_status_emails=NULL install_configure_form.enable_update_status_module=NULL

      - name: Get site and module version status
        run: |
            docker-compose exec -T cli php -v
            docker-compose exec -T cli drush st
            docker-compose exec -T cli drush pml